### ISSUE TITLE
Since yesterday my migrations have been failing

### ISSUE THREAD

**Issue by DaveKLloyd** [github/gh-gei#198]
I have been running migrations with octoshift 0.04 for weeks with no issue. 

As of yesterday I keep getting a Migration failed with this messsage.
[10:32 AM] [ERROR] Migration Failed. Migration ID: *****************************
[10:32 AM] [ERROR] Git source migration failed. Error message: SSL error: syscall failure: Broken pipe

Just realized there are things in the Logs that should not be in a public issue. If the logs are useful let me know and I will send them.

The command being run:

`octoshift migrate-repo --ado-org "ado-org" --ado-team-project "ado_project" --ado-repo "ado_repo" --github-org "github_org" --github-repo "gh_repo"`

The Repo gets created but it's empty. 

Is this just a network thing or is something else wrong?
FYI I grabbed the latest version and it's still happening.

**Comment by dylan-smith** [comment]
Can you try 0.03 and see if it works. If it does I can give some more details and a better option than using an old version of the CLI.

**Comment by DaveKLloyd** [comment]
Version 3 worked. :)

**Comment by dylan-smith** [comment]
So a bit of context on what's going on if you're interested. In mid-December the importer backend changed how it pushes your git repo into GitHub - it used to use SSH, then it changed to use HTTPS. The API's still support both methods, but the intent is to deprecate the SSH method.

In the CLI v0.4 we switched to use the HTTPS version of the API's.

SSH vs HTTPS is really not something our customers should need to know or care about, but in this case we've been finding some repos that have problems when using the new HTTPS method that just work with the old SSH approach.

So v0.3 of the CLI worked for you because it uses the old SSH approach.

We plan to add a --ssh flag to the CLI (hopefully on Monday's 0.6 release) that would allow users to use the latest CLI version, but force it to use the old SSH-based API's until the team resolves the HTTPS problems.

**Comment by DaveKLloyd** [comment]
@dylan-smith  

Thank you for the explanation that is very helpful.
