### ISSUE TITLE
generate-script command does not pick up GHES API URL

### ISSUE THREAD

**Issue by jschanfung** [github/gh-gei#273]
## Description

Happened when attempting migration from GHES -> GHEC/EMU

It looks like `gh gei generate-script` command [assumes source is always on github.com](https://github.com/github/gh-gei/blob/main/src/gei/Commands/GenerateScriptCommand.cs#L172)

<img width="1418" alt="Screen Shot 2022-03-17 at 3 44 03 pm" src="https://user-images.githubusercontent.com/61316020/158738930-45db3dbe-b80d-4804-ace3-467ffd74b22d.png">

**Comment by dylan-smith** [comment]
I see the problem in the code, and I will fix it. But before I do that I'm trying to understand how this ever worked.

@oakeyc @petermeglis do you know if/how generate-script ever worked against a GHES server?

**Comment by petermeglis** [comment]
I believe this was the PR that added this functionality: https://github.com/github/gh-gei/pull/248

IIRC we never got the chance to test on an actual GHES instance because we were waiting for backports or something of the sort in order to patch the instance.

This was probably just an oversight on my part

**Comment by oakeyc** [comment]
Thanks for the fix @dylan-smith ! I tested the migrate-repo against ES, but I don't think I tested the `generate-script` which was gap on my part! Let us know if you want any assistance on the patch.
