### ISSUE TITLE
Branch Protection not being migrated

### ISSUE THREAD

**Issue by DaveKLloyd** [github/gh-gei#757]
## Description
Getting an error on migration

I am running **gh ado2gh v0.31**

No Branch Policies are being migrated. 

I have this error in my migration log
[2022-12-09T21:35:45Z] INFO -- Import started
[2022-12-09T21:35:46Z] WARN -- LoadProtectedBranchJob: Protected Branch for branch name master could not be imported.
[2022-12-09T21:35:57Z] INFO -- Import complete

## Reproduce 
Migrate a Repo with the following master branch policies to a github or with default branch set to master. 
![image](https://user-images.githubusercontent.com/18465835/206800852-8ea2b7f4-f8c7-478c-ae3e-0bb1544cd53d.png)

**Comment by dylan-smith** [comment]
This appears to be a failure in our migration backend service (not the CLI - which is what this repo is focused on). I'm assuming this because the warning message you included is something only the backend service generates.

The best way to get help with this is to create a GitHub support ticket and it will get routed to the appropriate people.
