### ISSUE TITLE
Handling of username mentions in issue/comment bodies when migrating

### ISSUE THREAD

**Issue by FISHMANPET** [github/gh-gei#776]
## Description

I'm exploring this tool for migrating from a GitHub Enterprise Server instance to GitHub Enterprise Cloud.  I really like the user "mannequin" feature where admins have control over mapping GHES users to GHEC cloud users.  However, I'm noticing that when a user is mentioned in a comment, no translation is done.

In my test migration, we have internal usernames that already exist on GitHub.com, but are to accounts unrelated to us.  At best, we're spamming some random person with irrelevant notifications.  At worst, we could be potentially notifying some public user of our internal operations.  In our case, some of these users are still with the organization, and some aren't.  It would be nice if maybe these mentions were mapped to the same mannequin-type users that are used to create issues and comments.  That way we could "assign" the mention to the correct github.com user if they're still active in our company, or just ignore it and leave it as an unlinked mannequin if they're no longer with the company, but we still want a record of the person that made the comment.

I think this is more an issue with "GitHub Enterprise Importer" and not the CLI specifically, so if there's a better place to submit this feedback, please let me know and I can redirect.

**Comment by ArinGhazarian** [comment]
Hi @FISHMANPET 👋,

GEI currently doesn't support user mappings within a comment message so that would be a feature request. But regarding the security aspects of notifying mentioned users, non member users @mentioned in private repos don't get notified/subscribed. Same thing happens if you casually @mention someone in an issue comment not part of the org. 

cc: @timrogers for the feature request

**Comment by timrogers** [comment]
Hi @FISHMANPET! 👋🏻 I'm the Product Manager at GitHub for Migration Tools.

Thanks for taking the time to reach out with this feature request. Honestly, I'm surprised that it hasn't come up before! At the moment, we don't have any functionality that allows you to "remap" where a user is mentioned/tagged in a message. Using mannequins here would make a ton of sense.

We won't be able to implement this request in the short term, but it is definitely something I'll bear in mind for the future.

As you mentioned, this is an issue with our backend rather than with the CLI specifically, so I'm going to close this issue. But I will create an internal GitHub issue reflecting your request, and I'll make sure you're tagged, so we'll let you know as soon as we have any updates on this suggestion.

Thanks again for taking the time to get in touch!
