### ISSUE TITLE
Receiving a GraphQL error from `createMigrationSource` mutation triggers a `System.InvalidOperationException` with unhelpful error message

### ISSUE THREAD

**Issue by timrogers** [github/gh-gei#867]
## Description

When running `gh gei migrate-repo`, if the GraphQL `createMigrationSource` mutation responds with a `200 OK` with a GraphQL error, e.g.:

```json
{"data":{"createMigrationSource":null},"errors":[{"type":"FORBIDDEN","path":["createMigrationSource"],"extensions":{"saml_failure":true},"locations":[{"line":1,"column":109}],"message":"Resource protected by organization SAML enforcement. You must grant your Personal Access token access to this organization."}]}
```

...the CLI throws a `System.InvalidOperationException: Cannot access child value on Newtonsoft.Json.Linq.JValue.` and exits.

The underlying error message (`Resource protected by organization SAML enforcement. You must grant your Personal Access token access to this organization.`) is not visible unless they either (a) use the `--verbose` option or (b) manually check the verbose log file.

We should handle this case - and indeed other cases where the GraphQL API returns an error - by throwing an exception with the relevant error message.

## Reproduction Steps

Call the `gh gei migrate-repo` command with a target organization that requires the personal access token (PAT) to be enabled for SSO, but where the token hasn't been authorized for SSO.

**Comment by tgnanakumar** [comment]
We integrated [GitHub App Token](https://github.com/marketplace/actions/github-app-token) as part of our GitHub Action workflow automated using the IssueOps way (instead of using individual user personal access token) for migrating repositories from Azure DevOps to GitHub. However, we're facing a similar FORBIDDEN error as @timrogers but with a different message **Resource not accessible by integration** in the log. Are both of these the same issue or different? When I explicitly use a personal access token instead that is enabled and authorized for SSO, it works fine though. What are we missing here?

Here is the error printed in the log,
```
{
  "data": {
    "createMigrationSource": null
  },
  "errors": [
    {
      "type": "FORBIDDEN",
      "path": [
        "createMigrationSource"
      ],
      "extensions": {
        "saml_failure": false
      },
      "locations": [
        {
          "line": 1,
          "column": 109
        }
      ],
      "message": "Resource not accessible by integration"
    }
  ],
  "extensions": {
    "warnings": [
      {
        "type": "DEPRECATION",
        "message": "The id xxxxxxxxxxxxxx is deprecated. Update your cache to use the next_global_id from the data payload.",
        "data": {
          "legacy_global_id": "xxxxxxxxxxxxxx ",
          "next_global_id": "O_xxxxxxxx"
        },
        "link": "https://docs.github.com"
      }
    ]
  }
}
```

**Comment by timrogers** [comment]
@tgnanakumar Thanks for reaching out! I'm afraid that GitHub App tokens are not supported at this time for GitHub Enterprise Importer migrations. Only personal access tokens are supported. Sorry!
