### ISSUE TITLE
Clarify error message when AWS credentials are specified but not a bucket name

### ISSUE THREAD

**Issue by timrogers** [github/gh-gei#904]
When using `gh gei` or `gh bbs2gh` in blob storage mode, if you specify an AWS access key ID and secret access key via environment variables but omit the bucket name parameter, you get a not very clear error message:

> [11:06] [ERROR] Either Azure storage connection (--azure-storage-connection-string or AZURE_STORAGE_CONNECTION_STRING env. variable) or AWS S3 connection (--aws-bucket-name, --aws-access-key (or AWS_ACCESS_KEY_ID env. variable), --aws-secret-key (or AWS_SECRET_ACCESS_KEY env.variable)) must be provided.

We should make this error message more explicit and specific, telling you that you need to specify a `--aws-bucket-name`, e.g.:

> [11:06] [ERROR] --aws-bucket-name is required when an AWS credentials are specified.

## Reproduction steps

```
gh bbs2gh migrate-repo --bbs-server-url https://timrogers-bitbucket.expert-services.io/ \                                                                   
--bbs-project OS \
--bbs-repo litra \
--github-org "Deep-Avocado-9" \
--github-repo litra-20230322 --verbose --ssh-private-key ~/.ssh/bbs --ssh-user timrogers --ssh-port 122

**Comment by ArinGhazarian** [comment]
IMO this error message is clear enough, we are explicitly asking the user to provide either Azure connection string or all of the required AWS options. For AWS we say in which the `--aws-bucket-name` is the first arg:

> AWS S3 connection (--aws-bucket-name, --aws-access-key (or AWS_ACCESS_KEY_ID env. variable), --aws-secret-key (or AWS_SECRET_ACCESS_KEY env.variable)) must be provided.

I don't think it should cause any confusion and in your case the user should know that they have already set the secretes via environment variables so the missing bucket name is the problem. The reason I am double thinking about this is that those validations can get tricky and I don't want to make them any more complicated than they are right now. For example, in our validations we assume that if only the bucket name is not set they don't want to use AWS upload instead of checking for all possible AWS args (and env variables), and the reason is the AWS secret environment variables may have been already set on their machine simply because they use AWS for other stuff but might want to use Azure upload for the CLI, if we were to check all AWS args then it wouldn't be clear if they want to use Azure or AWS.

What do you think?

**Comment by timrogers** [comment]
I can definitely see the argument for not making these validations any more complex with additional branches and conditions - we already have pretty complex validations! I can also see your point about existing "passive" environment variables.

What do you think of rewriting the error message a bit to be clearer, but keeping the existing logic, e.g.:?

> Some AWS S3 connection settings were set, but required settings were missing. If you're using AWS S3, at a minimum, you must provided an AWS access key (--aws-access-key/AWS_ACCESS_KEY_ID), secret access key (--aws-secret-key/AWS_SECRET_ACCESS_KEY) and bucket name (--aws-bucket-name).

**Comment by ArinGhazarian** [comment]
Unfortunately that error message is not going to be accurate in this scenario, this validation kicks in only if the archive needs to be uploaded but none of the Azure storage nor AWS S3 credentials are set:
```c#
if (!shouldUseAzureStorage && !shouldUseAwsS3) { ... }
```
The current full error message is this:

> Either Azure storage connection (--azure-storage-connection-string or AZURE_STORAGE_CONNECTION_STRING env. variable) or
AWS S3 connection (--aws-bucket-name, --aws-access-key (or AWS_ACCESS_KEY_ID env. variable), --aws-secret-key (or AWS_SECRET_ACCESS_KEY env.variable))
must be provided.

**Comment by timrogers** [comment]
Ah, got it. Let's leave this for now. We can wait and see if we get more customer feedback to justify a change here. Thanks for your feedback!
