### ISSUE TITLE
redirect

### ISSUE THREAD

**Issue by Ajayos** [github/gh-gei#930]
iam make a new github account and change a old package from my old account to new account i want set redirect which is if any one take my old profile the will see the package and they cleck it that time it will redirect to new account and the package page using cmd

**Comment by timrogers** [comment]
@Ajayos Thanks for reaching out! Since this question is about GitHub rather than `gh-gei`, I'd recommend reaching out to [GitHub Support](https://support.github.com/?tags=dotcom-footer) with your question or asking in the [GitHub Community](https://github.com/orgs/community/discussions). I'm going to close this issue.
